"""Optional accounting-system adapters."""

from .fortnox import (
    DEFAULT_FORTNOX_BASE_URL,
    FortnoxAdapter,
    FortnoxAdapterError,
    FortnoxConfig,
    FortnoxDraftResult,
    FortnoxPolicyViolation,
    FortnoxProtectedOperation,
    FortnoxTransport,
    FortnoxTransportError,
    MissingFortnoxCredentials,
)
from .gnubok import (
    LocalGnubokShadowLedgerAdapter,
    ShadowAccount,
    ShadowCompanyContext,
    ShadowLedgerAdapter,
    ShadowLedgerComparison,
    ShadowLedgerLine,
    ShadowLedgerUnavailable,
    ShadowTransactionDraft,
    ValidationResult,
    default_shadow_ledger_adapter,
    mirror_supplier_invoice_proposal_to_shadow,
)

__all__ = [
    "DEFAULT_FORTNOX_BASE_URL",
    "FortnoxAdapter",
    "FortnoxAdapterError",
    "FortnoxConfig",
    "FortnoxDraftResult",
    "FortnoxPolicyViolation",
    "FortnoxProtectedOperation",
    "FortnoxTransport",
    "FortnoxTransportError",
    "LocalGnubokShadowLedgerAdapter",
    "MissingFortnoxCredentials",
    "ShadowAccount",
    "ShadowCompanyContext",
    "ShadowLedgerAdapter",
    "ShadowLedgerComparison",
    "ShadowLedgerLine",
    "ShadowLedgerUnavailable",
    "ShadowTransactionDraft",
    "ValidationResult",
    "default_shadow_ledger_adapter",
    "mirror_supplier_invoice_proposal_to_shadow",
]
